"""remove file_path

Revision ID: 11d5335dfd11
Revises: 7504d3936a68
Create Date: 2025-03-25 20:15:19.384895

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '11d5335dfd11'
down_revision: Union[str, None] = '7504d3936a68'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('announcements', 'files_path')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('announcements', sa.Column('files_path', sa.TEXT(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
