"""initial migration

Revision ID: 16a3f179734e
Revises: 
Create Date: 2025-02-16 19:32:18.543794

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '16a3f179734e'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('faqs', sa.Column('service_id', sa.Integer(), nullable=False))
    op.create_index(op.f('ix_faqs_service_id'), 'faqs', ['service_id'], unique=False)
    op.create_foreign_key(None, 'faqs', 'services', ['service_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'faqs', type_='foreignkey')
    op.drop_index(op.f('ix_faqs_service_id'), table_name='faqs')
    op.drop_column('faqs', 'service_id')
    # ### end Alembic commands ###
