"""add column

Revision ID: 17fa0297df3f
Revises: 
Create Date: 2025-03-21 14:52:36.137926

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '17fa0297df3f'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('announcements', sa.Column('platform', sa.String(length=255), nullable=False))
    op.add_column('announcements', sa.Column('links', sa.String(length=255), nullable=True))
    op.drop_column('announcements', 'qr_code')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('announcements', sa.Column('qr_code', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.drop_column('announcements', 'links')
    op.drop_column('announcements', 'platform')
    # ### end Alembic commands ###
