"""add foreign key in downloads

Revision ID: 24e07f9fc315
Revises: 9cdc87d09f27
Create Date: 2025-03-21 19:13:18.265027

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '24e07f9fc315'
down_revision: Union[str, None] = '9cdc87d09f27'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('downloads', sa.Column('service_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'downloads', 'categories', ['service_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'downloads', type_='foreignkey')
    op.drop_column('downloads', 'service_id')
    # ### end Alembic commands ###
