"""add user id in business information

Revision ID: 3a569ad0e194
Revises: f7a7c8e4ed4f
Create Date: 2025-06-27 06:40:20.186692

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3a569ad0e194'
down_revision: Union[str, None] = 'f7a7c8e4ed4f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_announcement_links_id', table_name='announcement_links')
    op.drop_table('announcement_links')
    op.drop_index('ix_service_attributes_id', table_name='service_attributes')
    op.drop_index('ix_service_attributes_service_id', table_name='service_attributes')
    op.drop_table('service_attributes')
    op.add_column('business_info', sa.Column('user_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'business_info', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'business_info', type_='foreignkey')
    op.drop_column('business_info', 'user_id')
    op.create_table('service_attributes',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('service_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('attribute_name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('attribute_value', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('attribute_type', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['service_id'], ['services.id'], name='service_attributes_service_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='service_attributes_pkey')
    )
    op.create_index('ix_service_attributes_service_id', 'service_attributes', ['service_id'], unique=False)
    op.create_index('ix_service_attributes_id', 'service_attributes', ['id'], unique=False)
    op.create_table('announcement_links',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('announcement_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('url', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('title', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['announcement_id'], ['announcements.id'], name='announcement_links_announcement_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='announcement_links_pkey')
    )
    op.create_index('ix_announcement_links_id', 'announcement_links', ['id'], unique=False)
    # ### end Alembic commands ###
