"""remove attr list

Revision ID: 72496e7f5f40
Revises: 830b8eab15a4
Create Date: 2025-03-23 23:11:51.595968

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '72496e7f5f40'
down_revision: Union[str, None] = '830b8eab15a4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_service_attribute_items_id', table_name='service_attribute_items')
    op.drop_table('service_attribute_items')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('service_attribute_items',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('attribute_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('step', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('order', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['attribute_id'], ['service_attributes.id'], name='service_attribute_items_attribute_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='service_attribute_items_pkey')
    )
    op.create_index('ix_service_attribute_items_id', 'service_attribute_items', ['id'], unique=False)
    # ### end Alembic commands ###
