"""add file_path in announcement

Revision ID: 7504d3936a68
Revises: c64dc715121c
Create Date: 2025-03-25 19:12:06.603879

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7504d3936a68'
down_revision: Union[str, None] = 'c64dc715121c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('announcements', sa.Column('image_path', sa.String(length=255), nullable=True))
    op.add_column('announcements', sa.Column('files_path', sa.Text(), nullable=True))
    op.drop_column('announcements', 'image')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('announcements', sa.Column('image', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.drop_column('announcements', 'files_path')
    op.drop_column('announcements', 'image_path')
    # ### end Alembic commands ###
