"""change download_id to file_path

Revision ID: 9cdc87d09f27
Revises: 17fa0297df3f
Create Date: 2025-03-21 18:24:30.811088

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9cdc87d09f27'
down_revision: Union[str, None] = '17fa0297df3f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('services', sa.Column('file_path', sa.String(length=255), nullable=True))
    op.drop_constraint('services_download_id_fkey', 'services', type_='foreignkey')
    op.drop_column('services', 'download_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('services', sa.Column('download_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('services_download_id_fkey', 'services', 'downloads', ['download_id'], ['id'], ondelete='SET NULL')
    op.drop_column('services', 'file_path')
    # ### end Alembic commands ###
