"""remove id in info attr

Revision ID: a1733ecd235a
Revises: 72496e7f5f40
Create Date: 2025-03-24 10:54:12.959342

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a1733ecd235a'
down_revision: Union[str, None] = '72496e7f5f40'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_business_info_attributes_business_info_id', table_name='business_info_attributes')
    op.drop_constraint('business_info_attributes_business_info_id_fkey', 'business_info_attributes', type_='foreignkey')
    op.drop_column('business_info_attributes', 'business_info_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('business_info_attributes', sa.Column('business_info_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('business_info_attributes_business_info_id_fkey', 'business_info_attributes', 'business_info', ['business_info_id'], ['id'], ondelete='CASCADE')
    op.create_index('ix_business_info_attributes_business_info_id', 'business_info_attributes', ['business_info_id'], unique=False)
    # ### end Alembic commands ###
