"""edit announcement

Revision ID: a8f5e4849908
Revises: 5fdccd62a0e7
Create Date: 2025-03-22 02:47:13.002500

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a8f5e4849908'
down_revision: Union[str, None] = '5fdccd62a0e7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('announcement_links',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('announcement_id', sa.Integer(), nullable=False),
    sa.Column('url', sa.String(length=255), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['announcement_id'], ['announcements.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_announcement_links_id'), 'announcement_links', ['id'], unique=False)
    op.drop_column('announcements', 'links')
    op.drop_column('announcements', 'labels')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('announcements', sa.Column('labels', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('announcements', sa.Column('links', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_announcement_links_id'), table_name='announcement_links')
    op.drop_table('announcement_links')
    # ### end Alembic commands ###
