"""add id in info attr

Revision ID: a91172a6b725
Revises: a1733ecd235a
Create Date: 2025-03-24 11:09:58.315314

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a91172a6b725'
down_revision: Union[str, None] = 'a1733ecd235a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('business_info_attributes', sa.Column('business_info_id', sa.Integer(), nullable=False))
    op.create_index(op.f('ix_business_info_attributes_business_info_id'), 'business_info_attributes', ['business_info_id'], unique=False)
    op.create_foreign_key(None, 'business_info_attributes', 'business_info', ['business_info_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'business_info_attributes', type_='foreignkey')
    op.drop_index(op.f('ix_business_info_attributes_business_info_id'), table_name='business_info_attributes')
    op.drop_column('business_info_attributes', 'business_info_id')
    # ### end Alembic commands ###
