"""remove file path

Revision ID: c64dc715121c
Revises: a91172a6b725
Create Date: 2025-03-25 02:32:15.190137

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c64dc715121c'
down_revision: Union[str, None] = 'a91172a6b725'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('services', 'file_path')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('services', sa.Column('file_path', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
