"""add foreign key in downloads

Revision ID: d2224bc05483
Revises: 24e07f9fc315
Create Date: 2025-03-21 19:16:28.958409

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd2224bc05483'
down_revision: Union[str, None] = '24e07f9fc315'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('downloads_service_id_fkey', 'downloads', type_='foreignkey')
    op.create_foreign_key(None, 'downloads', 'services', ['service_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'downloads', type_='foreignkey')
    op.create_foreign_key('downloads_service_id_fkey', 'downloads', 'categories', ['service_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###
