"""add image

Revision ID: d3e84e898d93
Revises: ba388da38362
Create Date: 2025-02-20 14:12:49.266961

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd3e84e898d93'
down_revision: Union[str, None] = 'ba388da38362'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('announcements', sa.Column('image_path', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('announcements', 'image_path')
    # ### end Alembic commands ###
