"""updated models

Revision ID: d9431cc7be42
Revises: ab2b366ca565
Create Date: 2025-02-13 19:46:56.393321

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd9431cc7be42'
down_revision: Union[str, None] = 'ab2b366ca565'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('requirements_category_id_fkey', 'requirements', type_='foreignkey')
    op.drop_column('requirements', 'category_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('requirements', sa.Column('category_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('requirements_category_id_fkey', 'requirements', 'service_categories', ['category_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###
