"""updated models

Revision ID: e633ab0a3da2
Revises: 5b2f723ae981
Create Date: 2025-02-13 21:18:38.961539

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e633ab0a3da2'
down_revision: Union[str, None] = '5b2f723ae981'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_services_user_id'), 'services', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_services_user_id'), table_name='services')
    # ### end Alembic commands ###
