"""adjust business information

Revision ID: f7a7c8e4ed4f
Revises: 36502d6fbe73
Create Date: 2025-06-22 16:44:03.595375

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f7a7c8e4ed4f'
down_revision: Union[str, None] = '36502d6fbe73'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_business_info_attributes_business_info_id', table_name='business_info_attributes')
    op.drop_index('ix_business_info_attributes_id', table_name='business_info_attributes')
    op.drop_table('business_info_attributes')
    op.add_column('business_info', sa.Column('tagline', sa.String(length=255), nullable=True))
    op.add_column('business_info', sa.Column('email', sa.String(length=255), nullable=True))
    op.add_column('business_info', sa.Column('phone', sa.String(length=50), nullable=True))
    op.add_column('business_info', sa.Column('website', sa.String(length=255), nullable=True))
    op.add_column('business_info', sa.Column('address', sa.Text(), nullable=True))
    op.add_column('business_info', sa.Column('city', sa.String(length=100), nullable=True))
    op.add_column('business_info', sa.Column('state', sa.String(length=100), nullable=True))
    op.add_column('business_info', sa.Column('country', sa.String(length=100), nullable=True))
    op.add_column('business_info', sa.Column('postal_code', sa.String(length=20), nullable=True))
    op.add_column('business_info', sa.Column('industry', sa.String(length=100), nullable=True))
    op.add_column('business_info', sa.Column('business_type', sa.String(length=50), nullable=True))
    op.add_column('business_info', sa.Column('founded_date', sa.DateTime(), nullable=True))
    op.add_column('business_info', sa.Column('employee_count_range', sa.String(length=50), nullable=True))
    op.add_column('business_info', sa.Column('business_hours', sa.Text(), nullable=True))
    op.add_column('business_info', sa.Column('timezone', sa.String(length=50), nullable=True))
    op.add_column('business_info', sa.Column('social_media', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('business_info', 'social_media')
    op.drop_column('business_info', 'timezone')
    op.drop_column('business_info', 'business_hours')
    op.drop_column('business_info', 'employee_count_range')
    op.drop_column('business_info', 'founded_date')
    op.drop_column('business_info', 'business_type')
    op.drop_column('business_info', 'industry')
    op.drop_column('business_info', 'postal_code')
    op.drop_column('business_info', 'country')
    op.drop_column('business_info', 'state')
    op.drop_column('business_info', 'city')
    op.drop_column('business_info', 'address')
    op.drop_column('business_info', 'website')
    op.drop_column('business_info', 'phone')
    op.drop_column('business_info', 'email')
    op.drop_column('business_info', 'tagline')
    op.create_table('business_info_attributes',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('business_info_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('attribute_name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('attribute_value', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('attribute_type', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['business_info_id'], ['business_info.id'], name='business_info_attributes_business_info_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='business_info_attributes_pkey')
    )
    op.create_index('ix_business_info_attributes_id', 'business_info_attributes', ['id'], unique=False)
    op.create_index('ix_business_info_attributes_business_info_id', 'business_info_attributes', ['business_info_id'], unique=False)
    # ### end Alembic commands ###
