"""Initial migration

Revision ID: f98fccd93452
Revises: 6047749269ac
Create Date: 2025-02-11 20:14:48.996576

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f98fccd93452'
down_revision: Union[str, None] = '6047749269ac'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('announcements', sa.Column('name', sa.String(length=255), nullable=False))
    op.add_column('announcements', sa.Column('description', sa.Text(), nullable=False))
    op.add_column('announcements', sa.Column('create_at', sa.DateTime(), nullable=True))
    op.add_column('requirement_categories', sa.Column('create_at', sa.DateTime(), nullable=True))
    op.add_column('requirements', sa.Column('create_at', sa.DateTime(), nullable=True))
    op.add_column('services', sa.Column('create_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('services', 'create_at')
    op.drop_column('requirements', 'create_at')
    op.drop_column('requirement_categories', 'create_at')
    op.drop_column('announcements', 'create_at')
    op.drop_column('announcements', 'description')
    op.drop_column('announcements', 'name')
    # ### end Alembic commands ###
